import type { Metadata } from "next"
import "./globals.css"
import { ReactNode } from "react"
import Providers from "@/app/Providers"
import Header from "@/components/global/Header/Header"
import "@flaticon/flaticon-uicons/css/all/all.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  manifest: "/manifest.webmanifest",
  icons: [
    {
      rel: "icon",
      type: "image/png",
      sizes: "16x16",
      url: "/favicon-16x16.png",
    },
    {
      rel: "icon",
      type: "image/png",
      sizes: "32x32",
      url: "/favicon-32x32.png",
    },
    {
      rel: "icon",
      type: "image/x-icon",
      url: "/favicon.ico",
    },
  ],
}
//sync
export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang="ru">
      <body className="dark text-foreground bg-background min-h-screen">
        <Providers>
          <Header />
          <main className="py-5">{children}</main>
        </Providers>
      </body>
    </html>
  )
}
