import type { Metadata } from "next"
import "./globals.css"
import { ReactNode } from "react"
import Providers from "@/app/Providers"
import Header from "@/components/global/Header/Header"
import "@flaticon/flaticon-uicons/css/regular/rounded.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: [
    {
      rel: "icon",
      type: "image/svg",
      sizes: "16x16",
      url: '/sync.svg'
    },
  ],
}
//sync
export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang="ru">
      <body className="dark text-foreground bg-background min-h-screen">
        <Providers>
          <Header />
          <main className="py-5">{children}</main>
        </Providers>
      </body>
    </html>
  )
}
